### ISSUE TITLE
'NoneType' object has no attribute 'required'

### ISSUE THREAD

**Issue by Mte90** [askvortsov1/dynamic-django-forms#23]
```
Traceback (most recent call last):
  File "/opt/forms/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/forms/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/forms/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/forms/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/forms/venv/lib/python3.6/site-packages/django/views/generic/edit.py", line 168, in get
    return super().get(request, *args, **kwargs)
  File "/opt/forms/venv/lib/python3.6/site-packages/django/views/generic/edit.py", line 133, in get
    return self.render_to_response(self.get_context_data())
  File "/opt/forms/forms/views.py", line 26, in get_context_data
    context = super().get_context_data(**kwargs)
  File "/opt/forms/venv/lib/python3.6/site-packages/django/views/generic/edit.py", line 66, in get_context_data
    kwargs['form'] = self.get_form()
  File "/opt/forms/venv/lib/python3.6/site-packages/dynamic_forms/views.py", line 23, in get_form
    form.fields[self.response_field].add_fields(json_data)
  File "/opt/forms/venv/lib/python3.6/site-packages/dynamic_forms/formfields.py", line 46, in add_fields
    self.fields += self._configure_new_fields(gen_fields_from_json(form_json))
  File "/opt/forms/venv/lib/python3.6/site-packages/dynamic_forms/utils.py", line 131, in gen_fields_from_json
    fields.append(process_field_from_json(field_json))
  File "/opt/forms/venv/lib/python3.6/site-packages/dynamic_forms/utils.py", line 113, in process_field_from_json
    setattr(field, attr, val)
AttributeError: 'NoneType' object has no attribute 'required'
```

**Comment by Mte90** [comment]
So the issue is with the hidden field that doesn't have so many fields if not only value

**Comment by Mte90** [comment]
So the issue is with the hidden field that doesn't have so many parameter if not only value, I am working on a patch
